### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by mcolyer** [atom/atom-shell-starter#32]
The [license file](https://github.com/atom/atom-shell-starter/blob/50e222975e472ed88d3ffbaac4b411bee798d708/LICENSE.md) is blank, so @paulcbetts I was wondering what license this project should be under.

**Comment by paulcbetts** [comment]
hwhoops, MIT license, same as Atom Shell - good catch

**Comment by mcolyer** [comment]
Thanks for adding the license, the only trouble is I'm fighting with line endings now. Git wants to convert it to unix line endings instead of windows line endings `warning: CRLF will be replaced by LF in LICENSE.md.`. Do you know what might be causing this?

**Comment by mcolyer** [comment]
Based on this [SO Answer](http://stackoverflow.com/a/15687910) it seems to be caused by the `.gitattributes` file, usually you can correct this with `.git/config` settings but here `.gitattributes` is taking precedent.

**Comment by paulcbetts** [comment]
This is the way it should be, .gitattributes should trump your settings. I pasted in the license via the GitHub web editor, did it ignore my .gitattributes setting? Who makes this crap anyways? :stuck_out_tongue_winking_eye:
