### ISSUE TITLE
Having troubles building on OSX

### ISSUE THREAD

**Issue by aackerman** [atom/atom-shell-starter#36]
Hi there,

I'm trying to start this project and running into errors. I cloned the current master at ffd008366d8fb89fc84708400e863a555b6daee9.

I've been able to run `script/bootstrap`, but when running `script/build`. The `bootstrap.py` script from atom-shell throws an error on running `git submodule update --init --recursive`. But attempting to run the `bootstrap.py` script directly was more revealing.

It appears to be attempting to checkout a commit that doesn't exist in the brightray project.

```
fatal: reference is not a tree: c96ee1ee1e2d1322c4d73be18f28c232587a43a2
Unable to checkout 'c96ee1ee1e2d1322c4d73be18f28c232587a43a2' in submodule path 'vendor/brightray'
```

Any idea how I can get past this?

**Comment by paulcbetts** [comment]
@aackerman I think that some commits were reclaimed in brightray, I'll patch this tonight

**Comment by MattouFP** [comment]
Having the same issue. Looks like it is refering to a commit in a pull request that was never merged:

https://github.com/dcposch/brightray/commit/c96ee1ee1e2d1322c4d73be18f28c232587a43a2
https://github.com/brightray/brightray/pull/92

**Comment by paulcbetts** [comment]
Give this a go now

**Comment by MattouFP** [comment]
Works like a charm with the latest atom-shell commit. Thanks!
