### ISSUE TITLE
Fails on Windows if path contains a space

### ISSUE THREAD

**Issue by MrMichaelJKelly** [atom/atom-shell-starter#44]
I inadvertently cloned to j:\Dropbox (Personal)\atom-shell (note the space) and got a cryptic error when running script\bootstrap.  Handling spaces in Windows paths is really hard so you should probably just document in the Readme.MD that you shouldn't do this.

**Comment by paulcbetts** [comment]
Can you give me the error? I'd rather just fix it

**Comment by MrMichaelJKelly** [comment]
J:\Dropbox (Personal)\atom-shell>script\bootstrap
Node: v0.12.0
npm: v1.4.28
Python: v2.7.8
Installing build modules...
{ cwd: 'J:\\Dropbox (Personal)\\atom-shell\\build',
  ignoreStdout: true }
J:\Dropbox (Personal)\atom-shell\build\node_modules\.bin\npm --userconfig=J:\Dro
pbox (Personal)\atom-shell\.npmrc install --quiet
'J:\Dropbox' is not recognized as an internal or external command,
operable program or batch file.
J:\Dropbox (Personal)\atom-shell>


Note that I modified bootstrap to echo the command to help diagnose this.  
diff --git a/script/bootstrap b/script/bootstrap
	index 4f976c0..d5f0d1d 100755
	--- a/script/bootstrap
	+++ b/script/bootstrap
	@@ -19,7 +19,9 @@ function executeCommands(commands, done, index) {
         var options = null;
         if (typeof command !== 'string') {
           options = command.options;
    +      console.log(options);
           command = command.command;
    +      console.log(command);
         }
         safeExec(command, options, executeCommands.bind(this, commands, done, index
       }
