### ISSUE TITLE
Set up unit tests

### ISSUE THREAD

**Issue by paulcbetts** [atom/atom-shell-starter#6]

**Comment by stefanbuck** [comment]
I've started the implementation and help / feedback is welcome https://github.com/stefanbuck/atom-shell-starter/tree/add-tests

**The goals are:**
- [ ] Add Jasmine for the render / "front-end"
- [ ] Add Mocha or something similar for the browser / "back-end"
- [ ] Set up for Travis
  - [ ] Mac
  - [ ] Windows
  - [ ] Linux

**Comment by paulcbetts** [comment]
@stefanbuck This Issue title is super unclear, mostly it was a note to myself. This TODO isn't to set up unit tests for `atom-shell-starter` *itself*, it's to set up the framework for people who *use* atom-shell-starter to write unit tests for their apps. i.e. the end goal is, that someone using atom-shell-starter can just start writing Jasmine tests, then run `script/test` or something and see them pass/fail. 

The TODO would look something like (copied from the non-OSS app I'm writing where we did this):

- [ ] Set up the build system for tests 
- [ ] Rig up app startup so that we can run tests
- [ ] Set up the test framework inside a Renderer context
- [ ] Rig a menu item that will run unit tests on-demand
- [ ] Pop a Window with Jasmine rigged up which starts executing tests
- [ ] Port the Atom spec runner Grunt task

**Comment by stefanbuck** [comment]
Ahh now I understand. Sound pretty good and I need this :) Any plans to implement this "soon"? If you need help shout.

**Comment by mcolyer** [comment]
I'm looking for this as well so might take a stab at this.
